FORMAT: 1A
HOST: http://52.192.215.150:8080/api

# TaskRPG

Polls is a simple API allowing consumers to view polls and vote in them.

## Tasks Collection [/tasks]

### List All Tasks [GET]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "name": "test"
            }
        ]

### Create a New Task [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
           
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
              
            }
