FORMAT: 1A
HOST: http://52.192.215.150:8080

# TaskRPG

This TaskRPG private APIs.

#Const
## Task Type
>
0
>
1 
>
2 
>
3 
>
4 

## Task Status
>
0 available
>
1 finished
>
2 accept
>
3 doing
>
4 abandon

##Error States
>
0
>
1 
>
2 
>
3 
>
4

##Response Code
>
200 ok
>
201 Created
>
202 Accepted
>
204 No-Content
>
301 ???
>
400 Bad Request
>
401 Unauthorized
>
403 Forbidden
>
404 Not Found
>
500 Internal Server Error
>
502 Bad Gateway
>
503 Service Unavailable

## Time format ISO 8601
yyyy-MM-ddTHH:mm:ssZ

## Login [/oauth/token]

### Login with FB [POST]

+ Request (application/x-www-form-urlencoded)

        { 
            "grant_type": "password",
            "username": "855726924439531",
            "password": "<FB_ACCESS_TOKEN>"
        }
        
+ Response 200 (application/json)

        {
          "token_type": "bearer",
          "access_token": "1369edf055794acd6843752dc48892141922ace2",
          "expires_in": 3600
        }
## Tasks Collection [/api/tasks?index=0&size=20&count=false]

### List All Tasks [GET]

+ Request
    + Headers
    
            Authorization: Bearer <$TASKRPG_ACCESS_TOKEN>

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": 1,
                "title": "",
                "creator": {
                    "id": 1,
                    "name": "Matt Chang",
                    "image_url": "http://xxx.xxx.xxx"
                },
                "type": 0,
                "desc": "xxxxxxxxxxxxxxx",
                "creat_at": "2016-01-01T23:59:59Z", 
                "update_at": "2016-01-01T23:59:59Z",
                "status": 0,
                "subtask": [
                    1,
                    2,
                    4,
                    6
                ],
                "award": {
                    "id": 1,
                    "title": "Award_1",
                }
            }
        ]

### Create a New Task [POST]

+ Request (application/json)

        {
            "title": "xxx",
            "desc": "xxxxxx",
            "type": 1,
            "subtask": [
                    1,
                    2,
                    4,
                    6
            ],
            "award": {
                "id": 1,
                "title": "Award_1",
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /task/2

    + Body

            {
              
            }

## Tasks Collection [/tasks/1]

### Update Task [PUT]

+ Request (application/json)

        {
            "title": "xxx",
            "desc": "xxxxxx",
            "type": 1,
            "subtask": [
                    1,
                    2,
                    4,
                    6
            ],
            "award": {
                "id": 1,
                "title": "Award_1",
            }
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "title": "",
            "creator": {
                "id": 1,
                "name": "Matt Chang",
                "image_url": "http://xxx.xxx.xxx"
            },
            "type": 0,
            "desc": "xxxxxxxxxxxxxxx",
            "creat_at": "2016-01-01T23:59:59Z", 
            "update_at": "2016-01-01T23:59:59Z",
            "status": 0,
            "subtask": [
                1,
                2,
                4,
                6
            ],
            "award": {
                "id": 1,
                "title": "Award_1",
            }
        }
        
### Delete Task [DELETE]

+ Request (application/json)

+ Response 204 (application/json)